[TOC]

错误处理在开发过程中是必须要做的事，但如果代码中到处都是错误处理，使读者无法看清核心逻辑，那么就是错误的做法。

代码是可读的，但也要强固，可读与强固并不冲突，如果将错误处理隔离看待，独立于主要逻辑之外，就能写出强固而整洁的代码。做到这一步，我们就能单独的处理它，也可以极大的提升代码的可维护性。

# 使用`try-catch`
使用返回码意味着要在代码中自己进行错误判断和处理，这样核心业务和错误处理就会混杂在一起。

因此更推荐使用`try-catch`语句，遇到错误直接抛错，交由`catch`语句处理。

好处在于try语句范围内的是核心业务代码，`catch`语句返回内是错误处理代码。

，错误处理交由`catch`语句。这种做法不仅会使得代码更整洁，还将核心算法和错误处理分离了，我们可以查看其中任一主题，分别进行理解

# 使用未检异常
`java`中存在已检异常。
> 了解下java中的已检异常是怎么回事...

# 给出异常发生的环境说明
我们抛出的每个异常，都应该提供足够的环境说明，以便判断错误的位置和来源。

# 依调用者需要定义异常类
对异常分类有很多种方式，根据来源分类、根据类型分类都是合理的。不过，我们定义异常类时，更重要的考虑是**如何捕获异常**

首先看一个不太好的做法：
```js
const port = new ACMEPort(12);

try{
    port.open();
}catch(e){
    if(e instanceof DeviceResponseException){
        reportPortError(e);
        console.log('Device response exception',e);
    }
    if(e instanceof ATM1212UnlockedException){
        reportPortError(e);
        console.log('Unlock exception',e);
    }
    if(e instanceof GMXError){
        reportPortError(e);
        console.log('Device response exception',e);
    }
}
```

重构下这段代码：
```js
const port = new ACMEPort(12);

try{
    port.open();
}catch(e){
    if(e instanceof PortDeviceFailure){
        reportPortError(e);
        console.log(e.getMessage(),e);
    }
}

class LocalPort{
    //...

    open(){
        try{
            innerPort.open();
        }catch{
            if(e instanceof DeviceResponseException){
                throw new PortDeviceFailure('Device response exception',e);
            }
            if(e instanceof ATM1212UnlockedException){
                throw new PortDeviceFailure('Unlock exception',e);
            }
            if(e instanceof GMXError){
                throw new PortDeviceFailure('Device response exception',e);
            }
        }
    }
}
```
重构后的代码由`open`方法负责捕获并翻译抛出的异常

将错误捕获并依据不同情况报错的功能打包进第三方API，而非在客户端进行不同处理，好处在于：
1. 降低了对第三方库的依赖，可以方便换成其他库
2. 测试更方便，可以更容易的模拟第三方库
3. 代码更整洁，更容易维护

# 定义常规流程
```js
try{
    const expenses = expenseReportDAO.getMeals(employee.getId());
    m_total += expenses.getTotal();
}catch{
    m_total += getMealPerDiem();
}
```
解释下这里的代码业务：如果消耗了餐食则计入总额，如果没有消耗，则员工得到当日的餐食补贴。

这里的异常打断了正常的业务逻辑，在catch中处理特殊业务场景。但实际上这不是一个特别好的做法，我们更期望这么写，以此摆脱了对异常的处理：
```js
const expenses = expenseReportDAO.getMeals(employee.getId());
m_total += expenses.getTotal();
```
关键之处在于，如果是特殊场景，则`expenses.getTotal()`返回的就是`getMealPerDiem()`，我们将异常的处理转移到了`expenses.getTotal()`中

这种手法叫做特例模式，创建一个类或配置一个对象，用于处理特例，这种手法的好处在于客户端（调用处）就不需要应对异常行为了，异常行为被封装到了特例对象中。

# 别返回null
> js中存在`undefined`类型，实际这里说的`null`是`undefined`和`null`
 
因为如果数据可能是`null`，则在调用数据时，都需要对`null`进行判断，使得业务逻辑不再纯粹，比如：
```js
const list = getList():
if(list !== null){
    list.forEach(x=>x+1);
}
```
如果我们可以保证`getList()`不会返回`null`，返回的必定是数组，那么业务逻辑会纯粹很多，比如：
> 这里也是特例模式的体现
```js
getList().forEach(x=>x+1);
```

# 别传递null
如果传递数据是null，则会破坏方法的执行，因此如果数据可能为null，则需要在方法中针对null进行额外错误处理。

因此，最好的做法还是任何时候都不要传递null，针对null的任何处理都会破坏核心算法的完整性，目前没有一个特别合适的针对null的处理方案。

我们首先希望不要传递null，如果做不到再考虑进行null的错误处理。

前端麻烦的地方在于数据不掌控在前端，而依赖于后端。但是如果我们在源头处控制数据，相对而言，后续null的错误处理可以减消一些，也是有益的做法。